Algoritmo "1a10"
// Disciplina   : [Linguagem e Lógica de Programação com visualG]
// Professor   : Jailson Santos
// Descrição   : Este programa exibe numeros de 1 a 10
// Autor(a)    : Marcelo Richard
// Data atual  : 08/04/2025
Var

   contador: inteiro


Inicio



   enquanto contador  < 11 faca
   escreva(contador)
      contador<- contador + 1
   fimenquanto


Fimalgoritmo