Algoritmo "AtéO20"
// Disciplina   : [Linguagem e Lógica de Programação com visualG]
// Professor   : Jailson Santos
// Descrição   : Este algoritimo mostra uma sequencia de 2 em 2 até o 20
// Autor(a)    : Marcelo Richard
// Data atual  : 08/04/2025
Var


   numero: real


Inicio

   numero<- 2

   enquanto numero <= 20 faca
      escreva(numero)
      numero<- numero + 2
   fimenquanto


Fimalgoritmo