Algoritmo "Númerosde1ate200"
// Disciplina   : [Linguagem e Lógica de Programação com VisualG]
// Professor   : Jailson Santos
// Descrição   : Soma os números de 1 até 200 se forem divisiveis por 4
// Autor(a)    : Marcelo Richard
// Data atual  : 26/03/2025
Var

contador: inteiro


Inicio

contador<- 1

enquanto contador < 200 faca
se contador mod 4 = 0 entao
escreval(contador)
fimse

contador<- contador +1
fimenquanto


Fimalgoritmo