Algoritmo "Regressiva"
// Disciplina   : [Linguagem e Lógica de Programação com visualG]
// Professor   : Jailson Santos
// Descrição   : Este programa faz uma contagem regressiva
// Autor(a)    : Marcelo Richard
// Data atual  : 08/04/2025
Var

contador, numero: real


Inicio

escreva("Digite um número: ")
leia(numero)

enquanto numero > 0 faca
numero<- numero - 1
escreva(numero)

fimenquanto



Fimalgoritmo