Algoritmo "ClasssificaçãoNúmerica"
// Disciplina   : [Linguagem e Lógica de Programação com VisualG]
// Professor   : Jailson Santos
// Descrição   : Este programa classifica um número.
// Autor(a)    : Marcelo Richard
// Data atual  : 22/03/2025
Var
   numero: Real


Inicio

   Escreva("Digite o número: ")
   Leia(numero)

   se numero >= 0 entao
      Escreva("Número positivio: ", numero)
   senão
      Escreva("Número negativo: ", numero)
   fimse




Fimalgoritmo