Algoritmo "PositivoNegativo"
// Disciplina   : [Linguagem e Lógica de Programação com visualG]
// Professor   : Jailson Santos
// Descrição   : Este algoritimo indica se um número é negativo ou positivo
// Autor(a)    : Marcelo Richard
// Data atual  : 29/03/2025
Var

numero: inteiro


Inicio


Escreva("Digite o número: ")
Leia(numero)


se numero > 0 entao
escreval("Numero positivo", numero)
senao
escreval("Numero negativo", numero)
fimse



Fimalgoritmo