Algoritmo "PositivoseNegativos"
// Disciplina   : [Linguagem e Lógica de Programação com VisualG]
// Professor   : Jailson Santos
// Descrição   : Verfifica se um número é negativo ou positivo e exibe no console
// Autor(a)    : Marcelo Richard
// Data atual  : 24/03/2025
Var
numero:inteiro

Inicio

Escreva("Escreva um número: ")
leia(numero)

se numero >=0 entao
escreva("Numero positivo")
senao
escreva("Numero negativo")
fimse



Fimalgoritmo