Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/03/2025
Var

contador: inteiro
numero: inteiro
multi: inteiro


Inicio

contador<-contador

Escreval("Digite um número: ")
Leia(numero)
enquanto contador <=10 faca
multi<-contador * numero
escreval(multi)
fimenquanto


Fimalgoritmo