Algoritmo "VerificarMaiorQueDez"
// Disciplina   : [Linguagem e Lógica de Programação com VisualG]
// Professor   : Jailson Santos
// Descrição   : Verifica se um número é maior ou menor que dez e diz isso no console
// Autor(a)    : Marcelo Richard
// Data atual  : 24/03/2025
Var

numero: inteiro
Inicio

Escreva("Escreva um número: ")
Leia(numero)

se numero > 10 entao
escreva("Número maior que 10!!!!")
senao
escreva("Numero menor que 10!!!!")
fimse


Fimalgoritmo