Algoritmo "Média"
// Disciplina   : [Linguagem e Lógica de Programação VisualG]
// Professor   : Jailson Santos
// Descrição   : Calcula a média de 3 notas
// Autor(a)    : Marcelo Richard
// Data atual  : 22/03/2025
Var
nota1: real
nota2: real
nota3: real
conta: real


Inicio

Escreva("Nota 1: ")
Leia(nota1)
Escreva("Nota 2: ")
Leia(nota2)
Escreva("Nota 3: ")
Leia(nota3)


conta<- (nota1 + nota2 + nota3 / 3)

Escreva("Sua média é: ", conta)




Fimalgoritmo