Algoritmo "NumeroImparPar2"
// Disciplina   : [Linguagem e Lógica de Programação com VisualG]
// Professor   : Jailson Santos
// Descrição   : Este programa analisa se um número é par ou impar
// Autor(a)    : Marcelo Richard
// Data atual  : 24/03/2025
Var

numero: real


Inicio

Escreva("Escreva um número positivo: ")
Leia(numero)

se numero mod 2 = 0 entao
Escreva("Numero par: ", numero)
senao
Escreva("Número impar: ", numero)
fimse



Fimalgoritmo