Algoritmo "Oantecessor"
// Disciplina   : [Linguagem e Lógica de Programação com JS]
// Professor   : Jailson Santos
// Descrição   : Este algoritimo pega um valor, e trás seu antecessor
// Autor(a)    : Marcelo Richard
// Data atual  : 17/03/2025
Var
valor1, valor2, ant: Real


Inicio
Escreva("Digite um numero boy:")
Leia(valor1)

ant<- valor1-1

Escreva("Antecessor:", ant)



Fimalgoritmo