Algoritmo "Osucessor"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/03/2025
Var
valor, suc: Real

Inicio

Escreva("Escreva um numero:")
Leia(valor)

suc<- valor + 1

Escreva("Seu sucessor:", suc)


Fimalgoritmo