Algoritmo "DesvioCondicionalComposto"
// Disciplina   : [Linguagem e Lógica de Programação com JS]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/03/2025
Var
   numero1: inteiro


Inicio

   Escreva("Digite um número: ")
   Leia(numero1)

   se numero1> 10 entao
      Escreva("Numero maior que 10")
   senao
      Escreva("Número menor que 10")
   fimse

Fimalgoritmo