Algoritmo "AreaDoCirculo"
// Disciplina   : [Linguagem e Lógica de Programação com JS]
// Professor   : Jailson Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Marcelo Richard
// Data atual  : 14/03/2025
Var
area, raio: Real


Inicio

Escreva("Raio do seu circulo:" )
Leia(raio)


area<- pi*raio*2

Escreva("Sua area é:", area)

Fimalgoritmo