Algoritmo "CalculoDaArea"
// Disciplina   : [Linguagem e Lógica de Programação com JS]
// Professor   : Marcelo
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/03/2025
Var

area, base, altura: Real


Inicio
Escreva("Qual a altura do seu retangulo:")
Leia(altura)
Escreva("Qual a base do seu retangulo:")
Leia(base)

area <- (base * altura)
Escreva("Sua area é:", area)



Fimalgoritmo